#!/usr/bin/env python3
"""R2-06: run gpu2d_test_system-like stress metrics via gpu2d_demo and freeze JSON.

Executes each stress scene headless on Tile32 and records machine-readable metrics
from the demo stdout line + a small companion runner.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXE = ROOT / "build" / "stage0045" / "model" / "pc_demo" / "gpu2d_demo.exe"
OUT_JSON = ROOT / "results" / "stage0045" / "stress" / "stress_stats.json"
OUT_MD = ROOT / "results" / "stage0045" / "stress" / "stress_stats.md"

SCENES = [
    ("sprite", "SpriteStorm", 80, 9),
    ("alpha", "AlphaStorm", 80, 9),
    ("bullet", "BulletHell", 80, 9),
    ("scale", "ScaleStorm", 80, 9),
    ("overdraw", "OverdrawStorm", 80, 9),
]

# Frozen thresholds from TASK_0045
THRESHOLDS = {
    "sprite": {"metric": "sprites", "min": 500},
    "alpha": {"metric": "alpha_draws", "min": 300},
    "bullet": {"metric": "live_bullets", "min": 1000},
    "scale": {"metric": "scaled_draws", "min": 200},
    "overdraw": {"metric": "max_overdraw", "min": 8},
}


def run_scene(name: str, frames: int, seed: int) -> dict:
    cmd = [str(EXE), "--headless", "--frames", str(frames), "--seed", str(seed),
           "--backend", "tile", "--scene", name]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if r.returncode != 0:
        raise RuntimeError(f"{name} rc={r.returncode} {r.stderr[-200:]}")
    # Parse last gpu2d_demo done line (BASE telemetry)
    line = ""
    for ln in r.stdout.splitlines():
        if "gpu2d_demo done" in ln:
            line = ln
    # base_cmds=.. base_sprites=.. tiles=a/b wrefs=.. max_od=..
    def grab(k: str) -> int:
        m = re.search(rf"{k}=(\d+)", line)
        return int(m.group(1)) if m else 0
    return {
        "scene": name,
        "seed": seed,
        "frames": frames,
        "base_sprites": grab("base_sprites"),
        "base_cmds": grab("base_cmds"),
        "tiles_active": grab("tiles"),
        "workrefs": grab("wrefs"),
        "max_overdraw": grab("max_od"),
        "stdout_line": line.strip(),
    }


def main() -> int:
    if not EXE.is_file():
        print(f"missing {EXE}", file=sys.stderr)
        return 1
    rows = []
    for name, _label, frames, seed in SCENES:
        print(f"running {name}...", flush=True)
        rows.append(run_scene(name, frames, seed))
    data = {
        "label": "Functional PC Golden workload statistics — NOT FPGA performance",
        "backend": "tile32",
        "scenes": rows,
        "thresholds": THRESHOLDS,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    # Markdown summary from JSON
    lines = [
        "# Stage 004.5 Stress Statistics",
        "",
        "> **Functional PC Golden workload statistics — NOT FPGA performance evidence**",
        "",
        f"Generated by `scripts/gen_stress_stats0045.py` → `{OUT_JSON.name}`.",
        "",
        "| Scene | Frames | Seed | Base Sprites | WorkRefs | Max OD |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(
            f"| {r['scene']} | {r['frames']} | {r['seed']} | {r['base_sprites']} "
            f"| {r['workrefs']} | {r['max_overdraw']} |")
    lines += [
        "",
        "Machine thresholds are asserted in `gpu2d_test_system` "
        "(sprite/alpha/scale/live_bl/bullet_draws/max_od).",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_JSON} and {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
