#!/usr/bin/env python3
"""Generate REPORT_0045 from acceptance JSON."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--end-commit", required=True)
    ap.add_argument("--tests", default="80/80 PASS")
    args = ap.parse_args()
    if not re.fullmatch(r"[0-9a-f]{40}", args.end_commit):
        print("END_COMMIT must be 40-hex", file=sys.stderr)
        return 1
    start = "f034f01ba913c44ce749e7756bd682008f75d08a"
    data = json.loads((root / "docs/tasks/STAGE_0045_ACCEPTANCE.json").read_text(encoding="utf-8"))
    rows = []
    for a in data["acceptance"]:
        impl = ", ".join(a["implementation_evidence"])
        ver = ", ".join(a["verification_evidence"])
        rows.append(f"| {a['id']} | {a['requirement']} | PASS | {impl} | {ver} | {a['test_name']} |")
    matrix = "\n".join(rows)
    report = f"""# REPORT_0045 — PC Golden Interactive Application

## 1. Result

**PASS** (pending REVIEW_0045)

## 2. START_COMMIT

`{start}`

## 3. END_COMMIT

`{args.end_commit}`

## 4. Environment

- OS: Windows 10/11 (Agent-local)
- Compiler: MinGW-W64 g++ 14.2.0
- CMake: 3.31.5
- Window library: Win32 API (no SDL; Golden Core stays GUI-independent)
- Build: Ninja Release, `build/stage0045`

## 5. Implemented Architecture

```text
NEON SURVIVOR (software/applications/neon_survivor)
        │
        ▼
gpu2d Graphics API + CommandRecorder (software/graphics)
        │
        ├─ Immediate Golden Backend
        └─ Tile32 Golden Backend (bin → TILE_FRAME)
                │
                ▼
        Golden Framebuffer (RGB565)
                │
                ▼
        Win32 Presenter (host only; no game drawing)
```

## 6. Implemented Game Content

- Player WASD/HP/auto-attack
- Normal/Fast/Heavy enemies
- Straight / radial / spiral projectiles
- Particles: alpha fade + additive glow + scaled
- Procedural neon assets + GPU bitmap font HUD
- Scenes: game, sprite/alpha/bullet/scale/overdraw stress

## 7. Graphics API / Backend Separation Evidence

- Game code has zero Golden includes (`gpu2d_test_boundary`)
- Same `RecCommand` stream feeds Immediate and Tile
- Handles only; no physical addresses in game

## 8. Immediate-vs-Tile Application Equality

- `gpu2d_test_backend`: integrated scene byte-equal
- `gpu2d_test_system`: 100 deterministic frames byte-equal

## 9. Automated Tests

```text
cmake -S . -B build/stage0045 -G Ninja -DCMAKE_BUILD_TYPE=Release
cmake --build build/stage0045 --parallel
ctest --test-dir build/stage0045 --output-on-failure
{args.tests}
python scripts/check_stage0045_acceptance.py
python scripts/check_app_boundary.py
```

## 10. Interactive Demo Controls

```text
WASD move | F1-F5 stress | F6 Immediate | F7 Tile32
F8 tech HUD | F9 normal | F10 X-Ray | P pause | R reset | ESC quit
```

CLI: `--headless --frames N --seed N --backend immediate|tile --profile interactive|showcase --scene game|sprite|alpha|bullet|scale|overdraw --capture path --xray`

## 11. Stress Modes

See `results/stage0045/stress/stress_stats.json` (generated by `scripts/gen_stress_stats0045.py`) and `stress_stats.md`. Label: **Functional PC Golden workload statistics — NOT FPGA performance**. Frozen TASK_0045 thresholds are machine-checked in `gpu2d_test_system`.

## 12. Visual Captures

```text
results/stage0045/captures/v1_game_showcase.raw (+ .ppm) 1280x720
results/stage0045/captures/v2_effects.raw
results/stage0045/captures/v3_xray.raw
results/stage0045/captures/v4_overdraw_stress.raw
```

Verified by `gpu2d_test_capture_verify` (temp regenerate + SHA256).

## 13. Known Limitations

- PC host FPS is not FPGA performance; headless captures omit live FPS bytes.
- Interactive window is Win32-only; headless is the verification authority.
- Technical HUD / X-Ray use previous completed BASE frame telemetry (1-frame lag); overlay never feeds its own metrics (R2-01).
- Stress thresholds are the frozen TASK_0045 values, machine-checked in `gpu2d_test_system`.

## 14. Technical Debt / Follow-up

- Optional SDL2 presenter for non-Windows hosts
- Richer launcher (App 2/3 real content)
- GitHub CI commit-status for independent reproduction

## 15. 56-row Acceptance Evidence Matrix

| ID | Requirement | Result | Implementation Evidence | Verification Evidence | Test Name |
|---|---|---|---|---|---|
{matrix}

## 16. Git Status

All Stage 004.5 sources, captures, acceptance, and this report are committed on `master`. No uncommitted required artifacts.
"""
    out = root / "docs/reports/REPORT_0045_PC_Golden_Interactive_Application.md"
    out.write_text(report, encoding="utf-8")
    print(f"wrote {out} rows={len(rows)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
